# Generated by Django 4.2.6 on 2023-12-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='name',
        ),
    ]
