# Generated by Django 4.2.6 on 2024-01-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_features_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
